#favicon
favicon: /images/favicon.png

# logo
logo: /images/logo.svg

# Header
menu:
  home: /
  #about: /about
  archives: /archives
  categories: /categories
  tags: /tags

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: false