#favicon
favicon: /images/favicon.png

# logo
logo: /images/logo.svg

# Header
menu:
  home: /
  #about: /about
  archives: /archives
  categories: /categories
  tags: /tags
language_list:
  us:
    name: English
    href: /
  tw:
    name: 繁體中文
    href: https://tw.benjamin.bekateam.com/

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: false